services:
  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4125
      - POSTGRES_DB=bookify

    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432" 



  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db
 
  bookify-idp:
   image: quay.io/keycloak/keycloak:latest
   container_name: Bookify.Identity
   command: start-dev --import-realm
   environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
   volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json
   ports:
      - 18080:8080


        
